//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class af_AuditLog
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public long relatedRowID { get; set; }
        public string relatedKeyCode { get; set; }
        public string relatedUserCode { get; set; }
        public string relatedDeptCode { get; set; }
        public string auditTypeCode { get; set; }
        public string flowCode { get; set; }
        public string startNodeCode { get; set; }
        public string nodeCode { get; set; }
        public string userCode { get; set; }
        public System.DateTime createDate { get; set; }
        public string passType { get; set; }
        public string printTag { get; set; }
        public string fromType { get; set; }
        public string recordType { get; set; }
        public Nullable<System.DateTime> auditDate { get; set; }
        public string auditResult { get; set; }
        public string auditRemark { get; set; }
        public string remark { get; set; }
    }
}
