//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class af_AuditNode
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string flowCode { get; set; }
        public string nodeCode { get; set; }
        public string nodeJson { get; set; }
        public string nodeDesc { get; set; }
        public string nodeType { get; set; }
        public string printTag { get; set; }
        public string passType { get; set; }
        public string auditUserCodes { get; set; }
        public string auditRoleCodes { get; set; }
        public string auditPostCodes { get; set; }
        public string selectUserCodes { get; set; }
        public string selectRoleCodes { get; set; }
        public string selectPostCodes { get; set; }
        public string editFieldCodes { get; set; }
        public string isNoteInform { get; set; }
        public string isEmailInform { get; set; }
        public string remark { get; set; }
    }
}
