//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class bks_Book
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string bookCode { get; set; }
        public string bookName { get; set; }
        public string isbnNO { get; set; }
        public Nullable<decimal> price { get; set; }
        public string authorName { get; set; }
        public string authorIntroduce { get; set; }
        public string bookIntroduce { get; set; }
        public string bookDirectory { get; set; }
        public string bookTypeCode { get; set; }
        public string pressCode { get; set; }
        public Nullable<System.DateTime> pressDate { get; set; }
        public string release { get; set; }
        public string surfacePic { get; set; }
        public string isSell { get; set; }
        public Nullable<int> stockSum { get; set; }
        public Nullable<int> sellSum { get; set; }
        public string remark { get; set; }
    }
}
