//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class bks_OrderDetail
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string orderCode { get; set; }
        public string bookCode { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<bool> isComment { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public string commentContent { get; set; }
    }
}
