//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class rbac_Resource
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string resourceCode { get; set; }
        public string resourceName { get; set; }
        public string moduleCode { get; set; }
        public string isShow { get; set; }
        public Nullable<int> showOrder { get; set; }
        public string haveOperations { get; set; }
        public string resourceUrl { get; set; }
        public string opControl { get; set; }
        public string dataControl { get; set; }
        public Nullable<int> pageWidth { get; set; }
        public Nullable<int> pagerCount { get; set; }
        public string remark { get; set; }
    }
}
