//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class rbac_ResourceOp
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string resourceCode { get; set; }
        public string operationCode { get; set; }
        public string operationName { get; set; }
        public Nullable<long> showOrder { get; set; }
    }
}
