//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class rbac_Module
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string moduleCode { get; set; }
        public string moduleName { get; set; }
        public string upModuleCode { get; set; }
        public string userType { get; set; }
        public Nullable<int> showOrder { get; set; }
        public string remark { get; set; }
    }
}
