//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_Org
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string orgCode { get; set; }
        public string orgName { get; set; }
        public string isDefault { get; set; }
        public string isWHOnline { get; set; }
        public string whOnlineValue { get; set; }
        public string sourceFrom { get; set; }
        public Nullable<System.DateTime> importDate { get; set; }
        public string remark { get; set; }
    }
}
