//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_WebLog
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public string logType { get; set; }
        public string userCode { get; set; }
        public string fromIP { get; set; }
        public string ipLoc { get; set; }
        public string fromLoc { get; set; }
        public string accessLoc { get; set; }
        public string requestType { get; set; }
        public string remark { get; set; }
    }
}
