//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_DataSyncInterface
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string sysTableName { get; set; }
        public string sysInsertTableName { get; set; }
        public string syskeyFieldName { get; set; }
        public string sourceTableName { get; set; }
        public string sourceTableJoinExpression { get; set; }
        public string sourceTableWhereExpression { get; set; }
        public string sourceTableOrderExpression { get; set; }
        public string isPrimary { get; set; }
        public string remark { get; set; }
    }
}
