//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_DataSyncInterfaceDetail
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string sysTableName { get; set; }
        public string sysFieldName { get; set; }
        public string sourceFieldName { get; set; }
        public string sourceFieldAliasName { get; set; }
        public Nullable<int> checkOrder { get; set; }
        public string show { get; set; }
        public string import { get; set; }
        public Nullable<int> showOrder { get; set; }
        public string filter { get; set; }
        public string remark { get; set; }
    }
}
