//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Column
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string resourceCode { get; set; }
        public string fieldCode { get; set; }
        public string fieldName { get; set; }
        public Nullable<bool> isShow { get; set; }
        public Nullable<int> showOrder { get; set; }
        public Nullable<bool> isOrder { get; set; }
        public Nullable<int> colWidth { get; set; }
        public Nullable<bool> isResize { get; set; }
        public string fixedValue { get; set; }
        public string alignType { get; set; }
        public string optionValue { get; set; }
        public string remark { get; set; }
    }
}
